// Crossword grid data - each cell is either a letter (the correct answer) or null (blank/black)
export const GRID = [
    ['S', 'H', 'R', 'O', 'U', 'D', null, null, 'E', null, 'L', null, 'F'],
    ['L', null, null, 'R', null, 'A', 'D', 'A', 'M', 'S', 'A', 'L', 'E'],
    ['I', null, 'S', 'A', 'R', 'I', null, null, 'E', null, 'T', null, 'I'],
    ['G', 'R', 'A', 'T', 'I', 'S', null, 'O', 'R', 'P', 'H', 'A', 'N'],
    ['H', null, 'N', 'O', 'D', null, 'F', null, 'A', 'L', 'E', 'R', 'T'],
    ['T', 'I', 'E', 'R', null, 'J', 'E', 'L', 'L', 'Y', null, 'E', null],
    [null, 'N', null, null, 'D', 'A', 'T', 'E', 'D', null, null, 'A', null],
    [null, 'A', null, 'H', 'A', 'B', 'I', 'T', null, 'V', 'E', 'S', 'T'],
    ['I', 'N', 'F', 'U', 'N', null, 'D', null, 'B', 'I', 'D', null, 'W'],
    ['S', 'E', 'L', 'E', 'C', 'T', null, 'N', 'E', 'G', 'A', 'T', 'E'],
    ['L', null, 'O', null, 'E', null, null, 'A', 'T', 'O', 'M', null, 'L'],
    ['A', 'C', 'C', 'U', 'R', 'A', 'C', 'Y', null, 'U', null, null, 'V'],
    ['M', null, 'K', null, 'S', null, null, 'S', 'O', 'R', 'T', 'I', 'E'],
];

export const ROWS = 13;
export const COLS = 13;

// Label positions: { number, row (1-indexed), col (1-indexed) }
export const LABELS = [
    { n: 1, r: 1, c: 1 },
    { n: 2, r: 1, c: 4 },
    { n: 3, r: 1, c: 6 },
    { n: 4, r: 1, c: 9 },
    { n: 5, r: 1, c: 11 },
    { n: 6, r: 1, c: 13 },
    { n: 7, r: 2, c: 6 },
    { n: 8, r: 3, c: 3 },
    { n: 9, r: 3, c: 5 },
    { n: 10, r: 4, c: 1 },
    { n: 11, r: 4, c: 8 },
    { n: 12, r: 4, c: 10 },
    { n: 13, r: 4, c: 12 },
    { n: 14, r: 5, c: 3 },
    { n: 15, r: 5, c: 7 },
    { n: 16, r: 5, c: 9 },
    { n: 17, r: 6, c: 1 },
    { n: 18, r: 6, c: 2 },
    { n: 19, r: 6, c: 6 },
    { n: 20, r: 6, c: 8 },
    { n: 21, r: 7, c: 5 },
    { n: 22, r: 8, c: 4 },
    { n: 23, r: 8, c: 10 },
    { n: 24, r: 8, c: 11 },
    { n: 25, r: 8, c: 13 },
    { n: 26, r: 9, c: 1 },
    { n: 27, r: 9, c: 3 },
    { n: 28, r: 9, c: 9 },
    { n: 29, r: 10, c: 1 },
    { n: 30, r: 10, c: 8 },
    { n: 31, r: 11, c: 8 },
    { n: 32, r: 12, c: 1 },
    { n: 33, r: 13, c: 8 },
];

// Clues
export const ACROSS_CLUES = [
    { n: 1, clue: 'Cover (6)' },
    { n: 7, clue: 'Water (5,3)' },
    { n: 8, clue: 'Indian Dress (4)' },
    { n: 10, clue: 'Without payment (6)' },
    { n: 11, clue: 'Parentless child (6)' },
    { n: 14, clue: 'Signal agreement (3)' },
    { n: 16, clue: 'Vigilant (5)' },
    { n: 17, clue: 'Row (4)' },
    { n: 19, clue: 'Wobbly dessert (5)' },
    { n: 21, clue: 'Unfashionable (5)' },
    { n: 22, clue: "Nun's outfit (5)" },
    { n: 23, clue: 'Singlet (4)' },
    { n: 26, clue: 'As a joke (2,3)' },
    { n: 28, clue: 'Offer (3)' },
    { n: 29, clue: 'Choose (6)' },
    { n: 30, clue: 'Nullify (6)' },
    { n: 31, clue: 'Particle of matter (4)' },
    { n: 32, clue: 'Precision (8)' },
    { n: 33, clue: 'A sally (6)' },
];

export const DOWN_CLUES = [
    { n: 1, clue: 'Slim (6)' },
    { n: 2, clue: 'Public speaker (6)' },
    { n: 3, clue: 'Podium (4)' },
    { n: 4, clue: 'Gemstone (7)' },
    { n: 5, clue: 'Turning tool (5)' },
    { n: 6, clue: 'Mock attack (5)' },
    { n: 8, clue: 'Sound of mind (4)' },
    { n: 9, clue: 'To free (3)' },
    { n: 12, clue: 'Fold (3)' },
    { n: 13, clue: 'Regions (5)' },
    { n: 15, clue: 'Stinking (5)' },
    { n: 18, clue: 'Senseless (5)' },
    { n: 19, clue: 'Quick short punch (3)' },
    { n: 20, clue: 'Permit (3)' },
    { n: 21, clue: 'Ballerinas (7)' },
    { n: 22, clue: 'Shade (3)' },
    { n: 23, clue: 'Vitality (6)' },
    { n: 24, clue: 'Dutch cheese (4)' },
    { n: 25, clue: 'Dozen (6)' },
    { n: 26, clue: 'Muslim religion (5)' },
    { n: 27, clue: 'Group of sheep (5)' },
    { n: 28, clue: 'Wager (3)' },
    { n: 30, clue: 'No votes (4)' },
];
